// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Assignment_WEBAPI_D6.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string username { get; set; }

    public string Photo { get; set; }

    [Column(TypeName = "money")]
    public decimal Salary { get; set; }

    public DateOnly Hiredate { get; set; }

    [Required]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }
    [NotMapped]
    public string Confirm_Password { get; set; }


    [ForeignKey("department")]
    public int DepartmentId { get; set; }
    public virtual Department department { get; set; }
}